Ipsilon WIP

diff --git a/tools/build-docker-image b/tools/build-docker-image
--- a/tools/build-docker-image
+++ b/tools/build-docker-image
@@ -19,6 +19,7 @@ Options:
 --namespace, -n <namespace>
 --tag, -t <tag>
 --push, -p
+--squash, -s
 --force-rm, -f
 --no-cache, -N
 --pull, -u
@@ -30,7 +31,7 @@ EOF
 [ -f $TOPDIR/.buildconf ] && . $TOPDIR/.buildconf
 [ -f $IMGDIR/.buildconf ] && . $IMGDIR/.buildconf
 
-ARGS=$(getopt -o hr:n:t:pfuN -l help,namespace:,push,private-registry:,release,tag:,force-rm,no-cache,no-use-released-parent -- "$@") || { usage >&2; exit 2; }
+ARGS=$(getopt -o hr:n:t:psfuN -l help,namespace:,push,squash,private-registry:,release,tag:,force-rm,no-cache,no-use-released-parent -- "$@") || { usage >&2; exit 2; }
 
 eval set -- "$ARGS"
 
@@ -48,6 +49,9 @@ while :; do
 
     (--tag|-t)  shift
                 TAG="$1"
+                ;;
+
+    (--squash|-s) SQUASH=1
                 ;;
 
     (--push|-p) PUSH=1
@@ -110,6 +114,7 @@ IMAGE="$PREFIX${IMGDIR##*/}"
 FULLIMAGE="$NAMESPACE/${IMAGE}${TAG:+:${TAG}}"
 
 DOCKER_FULLIMAGE="$RELEASE_NAMESPACE/${IMAGE}${TAG:+:${TAG}}"
+DOCKER_BUILDIMAGE="$RELEASE_NAMESPACE/${IMAGE}:build"
 
 cat <<EOF
 ======================================================================
@@ -132,15 +137,42 @@ sed -i.bak "s|%%DOCKER_NAMESPACE%%|$NAMESPACE|g" ${TMPDIR}/Dockerfile
 sed -i.bak "s|%%DOCKER_PREFIX%%|$PREFIX|g" ${TMPDIR}/Dockerfile
 sed -i.bak "s|%%DOCKER_TAG%%|$PARENT_TAG|g" ${TMPDIR}/Dockerfile
 sed -i.bak "s|%%DOCKER_BUILD_DATE%%|$(date -u +%Y-%m-%d)|g" ${TMPDIR}/Dockerfile
+PARENT_IMAGE=$(cat ${TMPDIR}/Dockerfile | grep -m1 "^FROM " | awk '{ print $2 }')
 
 
 
-if ! docker build ${BUILDFLAGS} -t "${FULLIMAGE}" ${TMPDIR}; then
-    echo "ERROR: failed to build ${FULLIMAGE}"
-    exit 1
+if [ "$SQUASH" = 1 ]; then
+
+    LAST_DOCKER_BUILDIMAGE_ID=$(docker inspect --format '{{ .Config.Image }}' ${DOCKER_BUILDIMAGE} | awk -F ':' '{ print $2 }' || true)
+    if ! docker build ${BUILDFLAGS} -t "${DOCKER_BUILDIMAGE}" ${TMPDIR}; then
+        echo "ERROR: failed to build ${DOCKER_BUILDIMAGE}"
+        exit 1
+    fi
+    DOCKER_BUILDIMAGE_ID=$(docker inspect --format '{{ .Config.Image }}' ${DOCKER_BUILDIMAGE} | awk -F ':' '{ print $2 }' || true)
+
+    if [[ "$LAST_DOCKER_BUILDIMAGE_ID" == "$DOCKER_BUILDIMAGE_ID" ]] ; then
+      echo "Squash: Build has not updated, skipping"
+    else
+      if [[ $PARENT_IMAGE == $NAMESPACE/* ]] ; then
+        if ! docker-squash "${DOCKER_BUILDIMAGE}" --from-layer "$PARENT_IMAGE" --tag "$FULLIMAGE" ; then
+            echo "ERROR: failed to squash ${FULLIMAGE}"
+            exit 1
+        fi
+      else
+        if ! docker-squash "${DOCKER_BUILDIMAGE}" --tag "$FULLIMAGE" ; then
+            echo "ERROR: failed to squash ${FULLIMAGE}"
+            exit 1
+        fi
+      fi
+      echo "Squashed: ${FULLIMAGE}"
+    fi
+else
+  if ! docker build ${BUILDFLAGS} -t "${FULLIMAGE}" ${TMPDIR}; then
+      echo "ERROR: failed to build ${FULLIMAGE}"
+      exit 1
+  fi
 fi
 rm -rf ${TMPDIR}
-
 echo "Built: ${FULLIMAGE}"
 
 if [ "$PUSH" = 1 ]; then
